# Planet Patrol
# =============
#
# Upptime-based monitoring using GitHub Actions

---

owner: nasa-pds-engineering-node
repo: PlanetPatrol

sites:
    -
        name: ðŸ¡Â PDS Website
        url: https://pds.nasa.gov/
    -
        name: :database:Â PDS Legacy Registry
        url: https://pds.nasa.gov/services/search/search?wt=json&q=product_class:Product_Collection
        __dangerous__body_degraded: '"numFound": 0'

    -
        name: :mag:Â PDS Search API
        url: https://pds.nasa.gov/api/search/1/products
        __dangerous__body_degraded: '"hits": 338711'


status-website:
    # We do not have a custom domain, so leaving `cname` blank:
    # cname:
    # Also, since we do not have a custom domain, so we need this `baseUrl`:
    baseUrl: /PlanetPatrol
    # Logo courtesy of Wojciech Ciecierski via Pixabay
    logoUrl: https://raw.githubusercontent.com/nasa-pds-engineering-node/PlanetPatrol/master/assets/planet-7123123.svg
    name: Planet Patrol
    introTitle: '**Planet Patrol** is a monitoring system for the Planetary Data System (demo)'
    introMessage: >
        The status of various Planetary Data System web sites, APIs, and other network
        endpoints is presented below.
    theme: light
    navbar:
        -
            title: Status
            href: /
        -
            title: Engineering Node
            href: https://pds-engineering.jpl.nasa.gov
        -
            title: GitHub
            href: https://github.com/$OWNER/$REPO

skipDescriptionUpdate: true
skipTopicsUpdate: true

...

# -*- mode: YAML; tab-width: 4 -*-
