---
owner: nasa-pds
repo: PlanetPatrol
sites:
  - name: pds.nasa.gov website
    url: https://pds.nasa.gov/?cloudfront=no
    assignees:
      - jordanpadams
      - viviant100
      - c-suh
      - tloubrieu-jpl
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: PDS Keyword Search and DOI Search (Legacy Registry)
    url: https://pds.nasa.gov/services/search/search?wt=json&q=product_class:Product_Collection&cloudfront=no
    assignees:
      - jordanpadams
      - viviant100
      - c-suh
      - rchenatjpl
      - tloubrieu-jpl
    expectedStatusCodes:
      - 200
    __dangerous__body_down: '"numFound":0'
    maxResponseTime: 5000

  - name: PDS Search API
    url: https://pds.nasa.gov/api/search/1/products
    assignees:
      - jordanpadams
      - viviant100
      - tloubrieu-jpl
      - sjoshi-jpl
    __dangerous__body_degraded: '"hits":0'
    maxResponseTime: 10000

  - name: PDS4 File System (System Bundle, Schemas, Context Products, etc.)
    url: https://pds.nasa.gov/data/pds4/
    assignees:
      - jordanpadams
      - viviant100
      - c-suh
      - rchenatjpl
      - tloubrieu-jpl
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

  - name: planetarydata.org website
    url: https://planetarydata.org
    assignees:
      - jordanpadams
      - nutjob4life
    maxResponseTime: 5000

  - name: pds-engineering.jpl.nasa.gov website
    url: https://pds-engineering.jpl.nasa.gov
    assignees:
      - jordanpadams
      - nutjob4life
      - viviant100
      - c-suh
    maxResponseTime: 5000

  - name: Legacy pds.jpl.nasa.gov domain
    url: https://pds.jpl.nasa.gov/
    assignees:
      - jordanpadams
      - viviant100
      - c-suh
      - tloubrieu-jpl
    expectedStatusCodes:
      - 200
    maxResponseTime: 5000

status-website:
  baseUrl: /PlanetPatrol
  logoUrl: https://raw.githubusercontent.com/NASA-PDS/PlanetPatrol/master/assets/PDS_Planets.png
  name: Planet Patrol
  introTitle: "**Planet Patrol** is a monitoring system for the Planetary Data System"
  introMessage: >
    The status of various Planetary Data System web sites, APIs, and
    other network endpoints is presented below.
  theme: light
  navbar:
    - title: Status
      href: /
    - title: Engineering Node
      href: https://pds-engineering.jpl.nasa.gov
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
delay: 2000
skipDescriptionUpdate: true
skipTopicsUpdate: true
...
