# Planet Patrol
# =============
#
# Upptime-based monitoring using GitHub Actions

---

owner: nasa-pds
repo: PlanetPatrol

sites:
    -
        name: pds.nasa.gov
        # Help avoid CloudFront and go right to the server by adding a request parameter
        url: https://pds.nasa.gov/?cloudfront=no
        assignees:
            - jordanpadams
            - viviant100
            - c-suh
            - tloubrieu-jpl
        expectedStatusCodes:
            - 200
        # Better respond in 5 seconds:
        maxResponseTime: 5000
    -
        name: PDS Legacy Registry
        url: https://pds.nasa.gov/services/search/search?wt=json&q=product_class:Product_Collection
        assignees:
            - jordanpadams
            - viviant100
            - c-suh
            - rchenatjpl
            - tloubrieu-jpl
        expectedStatusCodes:
            - 200
        __dangerous__body_down: '"numFound":0'

    -
        name: ds-view app (Tomcat)
        url: https://pds.nasa.gov/ds-view/pds/viewCollection.jsp
        assignees:
            - jordanpadams
            - viviant100
            - c-suh
            - rchenatjpl
            - tloubrieu-jpl
        expectedStatusCodes:
            - 200
        __dangerous__body_down: 'PDS Database is temporarily down for maintenance'
    -
        name: PDS Search API
        url: https://pds.nasa.gov/api/search/1/products?cloudfront=no
        assignees: # Users to assign downtime issues (optional)
            - jordanpadams
            - viviant100
            - tloubrieu-jpl
            - sjoshi-jpl
        __dangerous__body_degraded: '"hits":0' # Note this value is super super specific right now as our system is partially loaded
                                                     # we probably need to figure out a way to do some sort of range value here
                                                     # e.g. hits < 2000000
    -
        name: planetarydata.org
        url: https://planetarydata.org
        assignees:
            - jordanpadams
            - nutjob4life


status-website:
    # We do not have a custom domain, so leaving `cname` blank:
    # cname:
    # Also, since we do not have a custom domain, so we need this `baseUrl`:
    baseUrl: /PlanetPatrol
    logoUrl: https://raw.githubusercontent.com/NASA-PDS/PlanetPatrol/master/assets/PDS_Planets.png
    name: Planet Patrol
    introTitle: '**Planet Patrol** is a monitoring system for the Planetary Data System'
    introMessage: >
        The status of various Planetary Data System web sites, APIs, and other network
        endpoints is presented below.
    theme: light
    navbar:
        -
            title: Status
            href: /
        -
            title: Engineering Node
            href: https://pds-engineering.jpl.nasa.gov
        -
            title: GitHub
            href: https://github.com/$OWNER/$REPO

skipDescriptionUpdate: true
skipTopicsUpdate: true

...

# -*- mode: YAML; tab-width: 4 -*-
